# Generated by Django 4.0.5 on 2022-11-29 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_tokenmanager_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tokenmanager',
            old_name='user',
            new_name='main_user',
        ),
    ]
