# Generated by Django 4.0.5 on 2022-11-30 19:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0006_remove_messages_user_messages_reciever_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatuserlist',
            name='user',
        ),
        migrations.AddField(
            model_name='chatuserlist',
            name='main_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatuserlist',
            name='other_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
