# Generated by Django 4.0.5 on 2023-02-05 20:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0007_remove_chatuserlist_user_chatuserlist_main_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('thread_type', models.CharField(choices=[('personal', 'Personal'), ('group', 'Group')], default='group', max_length=15)),
                ('users', models.ManyToManyField(related_name='threads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='tokenmanager',
            name='main_user',
        ),
        migrations.RemoveField(
            model_name='tokenmanager',
            name='other_user',
        ),
        migrations.RenameField(
            model_name='messages',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='messages',
            name='message_content',
        ),
        migrations.RemoveField(
            model_name='messages',
            name='reciever',
        ),
        migrations.RemoveField(
            model_name='messages',
            name='token',
        ),
        migrations.AddField(
            model_name='messages',
            name='text',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='messages',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='messages',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='ChatList',
        ),
        migrations.DeleteModel(
            name='TokenManager',
        ),
        migrations.AddField(
            model_name='messages',
            name='thread',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.thread'),
        ),
    ]
