# Generated by Django 4.0.5 on 2023-02-05 20:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_thread_remove_tokenmanager_main_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 2, 5, 20, 31, 20, 290506, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
