# Generated by Django 4.0.5 on 2022-07-06 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='quantity_type',
            field=models.CharField(choices=[('Item', 'Item'), ('lbs', 'lbs'), ('oz', 'oz'), ('kg', 'kg'), ('g', 'g'), ('ml', 'ml')], default='Item', max_length=20),
        ),
    ]
