# Generated by Django 4.0.6 on 2022-07-20 04:55

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(choices=[('FALL', 'Fall'), ('WINTER', 'Winter'), ('SPRING', 'Spring'), ('SUMMER', 'Summer')], default='SPRING', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SoilType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soil_name', models.CharField(choices=[('LOAM', 'Loam'), ('SAND', 'Sand'), ('CLAY', 'Clay'), ('CHALK', 'Chalk')], max_length=20)),
                ('soil_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Soil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soil_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='soil', to='main.soiltype')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='soil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlantType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_name', models.CharField(max_length=255)),
                ('plant_scientific_name', models.CharField(max_length=255)),
                ('plant_description', models.TextField()),
                ('plant_type', models.CharField(max_length=200)),
                ('plant_size_max_height_lowest', models.DecimalField(decimal_places=2, max_digits=5)),
                ('plant_size_max_height_highest', models.DecimalField(decimal_places=2, max_digits=5)),
                ('plant_size_max_spread_lowest', models.DecimalField(decimal_places=2, max_digits=5)),
                ('plant_size_max_spread_highest', models.DecimalField(decimal_places=2, max_digits=5)),
                ('plant_max_size_time', models.DurationField()),
                ('plant_harvest_length', models.DurationField()),
                ('sun_exposer', models.CharField(choices=[('FULL_SUN', 'Full Sunlight'), ('PARTIAL_SUN', 'Partial Sunlight'), ('PARTIAL _OR_FULL_SUN', 'Full Sunlight or Partial Sunlight')], default='PARTIAL _OR_FULL_SUN', max_length=50)),
                ('weather_exposer', models.CharField(choices=[('EXPOSED', 'Exposed'), ('SHELTERED', 'Sheltered')], default='EXPOSED', max_length=50)),
                ('temperature_tolarence', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(-273.15), django.core.validators.MaxValueValidator(56.7)])),
                ('plant_moisture_level', models.CharField(choices=[('MOIST_BUT_WELL_DRAINED', 'Moist But Well Drained'), ('POORLY_DRAINED', 'Poorly Drained'), ('WELL_DRAINED', 'Well Drained')], default='WELL_DRAINED', max_length=50)),
                ('ph_level', models.CharField(choices=[('ACIDIC', 'Acidic'), ('ALKALINE', 'Alkaline'), ('NEUTRAL', 'Neutral')], default='NEUTRAL', max_length=20)),
                ('plant_how_to_cultivate', models.TextField()),
                ('plant_how_to_propagate', models.TextField()),
                ('plant_how_to_garden_type', models.TextField()),
                ('plant_how_to_pruning', models.TextField()),
                ('plant_how_to_pests', models.TextField()),
                ('plant_how_to_diseases', models.TextField()),
                ('plant_harvest_season', models.ManyToManyField(related_name='plant_harvest_season', to='main.season')),
                ('planting_season', models.ManyToManyField(related_name='plant_planting_season', to='main.season')),
                ('soil', models.ManyToManyField(related_name='plant', to='main.soiltype')),
            ],
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_current_size_height', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('plant_current_size_spread', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('planted_date', models.DateField()),
                ('image', models.ImageField(blank=True, null=True, upload_to=main.models.get_image_path)),
                ('plant_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plant', to='main.planttype')),
                ('soil_planted', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plant', to='main.soil')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plant', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
