# Generated by Django 4.0.5 on 2022-07-21 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planttype',
            name='sun_exposer',
            field=models.CharField(choices=[('FULL_SUN', 'Full Sunlight'), ('PARTIAL_SUN', 'Partial Sunlight'), ('FULL_OR_PARTIAL_SUN', 'Full Sunlight or Partial Sunlight')], default='FULL_OR_PARTIAL_SUN', max_length=50),
        ),
    ]
