# Generated by Django 4.0.5 on 2022-07-17 01:07

from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=main.models.get_image_path)),
                ('plants', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plant_image', to='main.plant')),
            ],
        ),
    ]
