# Generated by Django 4.0.5 on 2022-07-17 01:18

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_plantimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=main.models.get_image_path),
        ),
        migrations.DeleteModel(
            name='PlantImage',
        ),
    ]
