# Generated by Django 4.0.5 on 2022-07-17 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_plant_image_delete_plantimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='planted_date',
            field=models.DateField(),
        ),
    ]
